#!/bin/sh
#%# family=manual
#%# capabilities=autoconf suggest
case $1 in
    autoconf)
        exit 0
        ;;
    suggest)
        exit 0
        ;;
    config)
        echo graph_category odoo
        echo graph_title odoo workers recycling count
        echo graph_vlabel num workers recycling in last 5 minutes
        echo recycling.label num http recycling
        echo cron.label num cron recycling
        exit 0
        ;;
esac
# watch out for the time zone of the logs => using date -u for UTC timestamps
result=$(tail -60000 /var/log/odoo/odoo.log | grep -a "Worker WorkerHTTP" | grep -a "alive" | awk "BEGIN{count=0} (\$1 \" \" \$2) >= \"`date +'%F %H:%M:%S' -ud '5 min ago'`\" { count+=1; } END{print count/5}")
cronresult=$(tail -60000 /var/log/odoo/odoo.log | grep -a "Worker WorkerCron" | grep -a "alive" | awk "BEGIN{count=0} (\$1 \" \" \$2) >= \"`date +'%F %H:%M:%S' -ud '5 min ago'`\" { count+=1; } END{print count/5}")
echo "recycling.value ${result}"
echo "cron.value ${cronresult}"
exit 0
