#!/usr/bin/env bash
#%# family=manual

slave=`psql postgres -A -t -c "SELECT pg_is_in_recovery();"`
master=`psql postgres -A -t -c "SELECT count(client_addr) from pg_stat_replication;"`

if [[ $slave == "f" ]];
then
    if [[ $master -eq 0 ]];
    then
        exit 1
    else
        client=`psql postgres -A -t -c "SELECT client_addr from pg_stat_replication;"`
        client=`dig -x $client +short`
    fi
fi

case $1 in
    config)
        echo graph_category postgres
        echo graph_title Streaming Replication
        if [[ $master -gt 0 ]]; then
            echo delay_b.label Replication Lag \($client\)\(B\)
            echo delay_b.warning   10000000
            echo delay_b.critical 300000000
        fi
        if [[ $slave == "t" ]]; then
            echo graph_args --logarithmic --units=si
            echo delay_s.label Replication Delay \(s\)
            echo delay_s.warning   60
            echo delay_s.critical 600
            echo delay_b.label Replication Lag \(B\)
            echo delay_b.warning   10000000
            echo delay_b.critical 300000000
        fi
        exit 0
        ;;
esac

if [[ $master -gt 0 ]]; then
    # master
    echo -n "delay_b.value "
    psql postgres -A -t -c "select pg_xlog_location_diff(sent_location, replay_location) from pg_stat_replication;"
fi

if [[ $slave == "t" ]]; then
    # slave
    echo -n "delay_s.value "
    psql postgres -A -t -c "
    SELECT
    CASE
        WHEN pg_last_xlog_receive_location() = pg_last_xlog_replay_location() THEN 0
        ELSE EXTRACT (EPOCH FROM now() - pg_last_xact_replay_timestamp())
    END;"
    echo -n "delay_b.value "
    psql postgres -A -t -c "SELECT pg_xlog_location_diff(pg_last_xlog_receive_location(), pg_last_xlog_replay_location());"
fi

exit 0
